/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'on-error': '#ffffff',
        'surface-bright': '#fcf8fa',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#dce2f7',
        primary: '#000000',
        'on-tertiary-fixed-variant': '#55442d',
        'tertiary-fixed-dim': '#dcc2a4',
        'inverse-on-surface': '#f3f0f1',
        'primary-fixed-dim': '#c0c6db',
        'surface-container': '#f0edee',
        error: '#ba1a1a',
        'surface-variant': '#e5e2e3',
        'tertiary-container': '#261906',
        'surface-container-high': '#eae7e9',
        background: '#fcf8fa',
        'on-tertiary-fixed': '#261906',
        'on-secondary-fixed': '#151c27',
        'inverse-primary': '#c0c6db',
        'on-background': '#1b1b1d',
        'surface-dim': '#dcd9db',
        'tertiary-fixed': '#f9debf',
        outline: '#76777d',
        'on-tertiary-container': '#968065',
        'on-surface': '#1b1b1d',
        secondary: '#585f6c',
        'on-primary-container': '#7d8497',
        'on-secondary-fixed-variant': '#404754',
        'surface-container-low': '#f6f3f4',
        'on-tertiary': '#ffffff',
        'secondary-container': '#dce2f3',
        'secondary-fixed-dim': '#c0c7d6',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#45464c',
        'on-primary': '#ffffff',
        'secondary-fixed': '#dce2f3',
        surface: '#fcf8fa',
        'surface-tint': '#575e70',
        'on-primary-fixed': '#141b2b',
        'surface-container-highest': '#e5e2e3',
        'outline-variant': '#c6c6cd',
        'primary-container': '#141b2b',
        'on-secondary-container': '#5e6572',
        'on-error-container': '#93000a',
        'on-primary-fixed-variant': '#404758',
        'inverse-surface': '#303031',
        tertiary: '#000000',
        'error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'card-padding': '20px',
        'section-gap': '48px',
        unit: '4px',
        'container-padding': '32px',
      },
      fontFamily: {
        inter: ['Inter', 'ui-sans-serif', 'system-ui'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular'],
      },
    },
  },
  plugins: [],
};
